name: usb_device
description: Flutter plugin to communicate with usb device (start sessions, send datas, set configurations ...).
version: 1.0.2
repository: https://github.com/derekleiro/webUSB_plugin
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"
dependencies:
  flutter:
    sdk: flutter
  usb_device_web:
    git:
      url: https://github.com/derekleiro/webUSB_plugin.git
      path: usb_device_web
      ref: master
  usb_device_platform_interface:
    git: 
      url: https://github.com/derekleiro/webUSB_plugin.git
      path: usb_device_platform_interface
      ref: master

dependency_overrides:
  usb_device_web:
    git:
      url: https://github.com/derekleiro/webUSB_plugin.git
      path: usb_device_web
      ref: master
  usb_device_platform_interface:
    git: 
      url: https://github.com/derekleiro/webUSB_plugin.git
      path: usb_device_platform_interface
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        default_package: usb_device_web
