name: usb_device_web
description: A stub implementation of the Device usb plugin for Web. This package is used in usb_device plugin
version: 1.0.0
repository: https://github.com/derekleiro/webUSB_plugin
publish_to: none

environment:
  sdk: '>=3.3.0 <=3.9.0'
  flutter: ">=3.22.0"


flutter:
  plugin:
    platforms:
      web:
        pluginClass: WebUSBPlugin
        fileName: usb_device_web.dart
  assets:
    - assets/webusb.js

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  usb_device_platform_interface:
    git: 
      url: https://github.com/derekleiro/webUSB_plugin.git
      path: usb_device_platform_interface
      ref: master
  web: ^1.1.1

dependency_overrides:
  usb_device_platform_interface:
    git: 
      url: https://github.com/derekleiro/webUSB_plugin.git
      path: usb_device_platform_interface
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
